# Generated by Selenium IDE & Refined for TreeConnect Automated Testing
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

class TestLogin():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    # options.add_argument("--headless") # optional for headless CI runs
    self.driver = webdriver.Chrome(options=options)
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1280, 900)

    # Locate and interact with email input
    email_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.ID, "email"))
    )
    email_input.clear()
    email_input.send_keys("admintc@gmail.com")

    # Locate and fill password input (also dismisses email auto-suggestion overlay)
    password_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.ID, "password"))
    )
    password_input.clear()
    password_input.send_keys("Admin@123")

    # Click login submit button
    submit_btn = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".btn-block"))
    )

    # Scroll into view and click safely
    self.driver.execute_script("arguments[0].scrollIntoView(true);", submit_btn)
    time.sleep(0.3)
    try:
        submit_btn.click()
    except Exception:
        self.driver.execute_script("arguments[0].click();", submit_btn)

    time.sleep(1)
