# Generated by Selenium IDE & Refined for TreeConnect Automated Testing
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

class TestRequestharvest():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    # options.add_argument("--headless") # optional for headless CI runs
    self.driver = webdriver.Chrome(options=options)
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_requestharvest(self):
    # Step 1: Login as Landowner
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1280, 900)

    email_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.ID, "email"))
    )
    email_input.clear()
    email_input.send_keys("h4hari2003@gmail.com")

    password_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.ID, "password"))
    )
    password_input.clear()
    password_input.send_keys("password123")

    submit_btn = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".btn-block"))
    )
    self.driver.execute_script("arguments[0].scrollIntoView(true);", submit_btn)
    time.sleep(0.3)
    try:
        submit_btn.click()
    except Exception:
        self.driver.execute_script("arguments[0].click();", submit_btn)

    # Wait for post-login navigation to landowner portal
    WebDriverWait(self.driver, 10).until(
        EC.url_contains("/landowner")
    )

    # Step 2: Navigate to Harvest Requests Page
    self.driver.get("http://localhost:5173/landowner/harvest-requests")
    
    header_title = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.XPATH, "//h1[contains(text(), 'Harvest Requests')]"))
    )
    assert header_title is not None

    # Step 3: Open Request Harvest Wizard Page
    new_request_btn = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".ld-btn-action"))
    )
    try:
        new_request_btn.click()
    except Exception:
        self.driver.execute_script("arguments[0].click();", new_request_btn)

    # Confirm navigation to /landowner/request-harvest
    WebDriverWait(self.driver, 10).until(
        EC.url_contains("/landowner/request-harvest")
    )

    time.sleep(1)
