# Generated by Selenium IDE & Refined for TreeConnect Automated Testing
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

class TestInventorytree():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    # options.add_argument("--headless")
    self.driver = webdriver.Chrome(options=options)
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_inventorytree(self):
    # Step 1: Login as Landowner
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1280, 900)

    email_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.ID, "email"))
    )
    email_input.clear()
    email_input.send_keys("h4hari2003@gmail.com")

    password_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.ID, "password"))
    )
    password_input.clear()
    password_input.send_keys("password123")

    submit_btn = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".auth-form button[type='submit']"))
    )
    self.driver.execute_script("arguments[0].scrollIntoView(true);", submit_btn)
    time.sleep(0.3)
    try:
        submit_btn.click()
    except Exception:
        self.driver.execute_script("arguments[0].click();", submit_btn)

    time.sleep(2)

    # Step 2: Navigate to Tree Inventory page
    self.driver.get("http://localhost:5173/landowner/inventory")
    time.sleep(1)

    # Step 3: Click Add Tree Inventory button
    add_btn = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Add Tree Inventory') or contains(., 'Log Tree Inventory')]"))
    )
    add_btn.click()
    time.sleep(1)

    # Step 4: Fill Tree Inventory Form
    group_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//input[@placeholder='e.g. Frontyard Teak Stand']"))
    )
    group_input.clear()
    group_input.send_keys("Teak Standing")

    try:
        count_input = WebDriverWait(self.driver, 5).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@placeholder='e.g. 5' or @type='number']"))
        )
        count_input.clear()
        count_input.send_keys("5")
    except Exception:
        pass

    notes_input = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//input[contains(@placeholder, 'Mature teak')]"))
    )
    notes_input.clear()
    notes_input.send_keys("nothing")

    # Step 5: Save Tree Inventory
    save_btn = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.XPATH, "//button[@type='submit'][contains(., 'Save Tree Inventory')]"))
    )
    self.driver.execute_script("arguments[0].scrollIntoView(true);", save_btn)
    time.sleep(0.3)
    try:
        save_btn.click()
    except Exception:
        self.driver.execute_script("arguments[0].click();", save_btn)

    time.sleep(2)

  
