# Generated by Selenium IDE 
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProperties():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_properties(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1054, 848)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("h4hari2003@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("password123")
    self.driver.find_element(By.CSS_SELECTOR, ".auth-form button[type='submit']").click()
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".sidebar-group:nth-child(1) > .sidebar-item:nth-child(3) > span"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-group:nth-child(1) > .sidebar-item:nth-child(3) > span").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".ld-btn-green").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "propertyName").click()
    self.driver.find_element(By.NAME, "propertyName").send_keys("Teak Forest Estate")
    self.driver.find_element(By.NAME, "totalArea").click()
    self.driver.find_element(By.NAME, "totalArea").send_keys("11")
    dropdown = self.driver.find_element(By.NAME, "areaUnit")
    dropdown.find_element(By.XPATH, "//option[. = 'Cents']").click()
    self.driver.find_element(By.NAME, "approxTreesCount").click()
    self.driver.find_element(By.NAME, "approxTreesCount").send_keys("1")
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("nil")
    self.driver.find_element(By.CSS_SELECTOR, ".ld-risk-card:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ld-risk-card:nth-child(4) > .ld-risk-checkbox").click()
    self.driver.find_element(By.NAME, "riskNotes").click()
    self.driver.find_element(By.NAME, "riskNotes").send_keys("nil")
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("teak tree")
    # Click Register Property button to complete registration
    submit_btn = WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.XPATH, "//button[contains(., 'Register Property')]"))
    )
    submit_btn.click()
    time.sleep(2)
  
